### ISSUE TITLE
drizzle vs drizzle:p

### ISSUE THREAD

**Issue by md-redwan-hossain** [drizzle-team/drizzle-northwind-benchmarks-pg#5]
What is the difference between drizzle and drizzle:p? I don't find any explanation in the docs. Can anyone kindly clarify it?

**Comment by samuel-morrissey** [comment]
Pleeeese

**Comment by AlexanderArvidsson** [comment]
`drizzle:p` stands for Prepared Statements. You can read more about it on the docs: https://orm.drizzle.team/docs/rqb#prepared-statements
